name: Security Audit

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-security-checks:
    # Syntax: org-name/repo-name/.github/workflows/file-name.yml@ref
    uses: reconzo/ci-workflows/.github/workflows/sca-scan.yml@main
  run-dependency-review:
    # Syntax: org-name/repo-name/.github/workflows/file-name.yml@ref
    uses: reconzo/ci-workflows/.github/workflows/dependency-review.yml@main
